import { Product } from '@/app/api/types/products/products';

export const mockProducts: Product[] = [
  // 강아지
  {
    id: 1,
    name: '6free 강아지 사료 치킨 레시피',
    weight: '6kg',
    quantity: '1개',
    price: '30,000원',
    discountPrice: '24,000원',
    expiration: '25.10.10까지',
    category: '강아지',
    image: '/images/products/dogfood.png',
    details: [
      '고단백 & 저지방: 강아지의 에너지와 근육 유지에 중요한 고단백 재료 사용',
      '6FREE 레시피: 인공 색소, 향료, 방부제, 밀, 옥수수, 콩 무첨가',
      '연령별 맞춤: 모든 생애주기 강아지에 적합',
    ],
    location: '서울특별시 신림동',
    distance: '10km',
    shopName: 'ㅇㅇ동물병원',
    shopLocation: '서울특별시 관악구 신림로 123',
    shopDistance: '10km',
    shopImage: '/images/shops/shop1.png',
    phoneNumber: '05049763241',
  },
  {
    id: 2,
    name: '강아지 간식 치즈볼',
    weight: '500g',
    quantity: '2개',
    price: '15,000원',
    discountPrice: '12,000원',
    expiration: '25.12.01까지',
    category: '강아지',
    image: '/images/products/dog-snack.png',
    details: [
      '치즈 풍미 가득, 간식으로 적합',
      '소포장으로 신선도 유지',
      '모든 연령 강아지에게 적합',
    ],
    location: '서울특별시 강남구',
    distance: '12km',
    shopName: '강남동물병원',
    shopLocation: '서울특별시 강남구 테헤란로 45',
    shopDistance: '12km',
    shopImage: '/images/shops/shop2.png',
    phoneNumber: '05049763241',
  },
  {
    id: 3,
    name: '강아지 간식 치즈볼',
    weight: '500g',
    quantity: '2개',
    price: '15,000원',
    discountPrice: '12,000원',
    expiration: '25.12.01까지',
    category: '강아지',
    image: '/images/products/dog-snack2.png',
    details: [
      '치즈 풍미 가득, 간식으로 적합',
      '소포장으로 신선도 유지',
      '모든 연령 강아지에게 적합',
    ],
    location: '서울특별시 강남구',
    distance: '12km',
    shopName: '강남동물병원',
    shopLocation: '서울특별시 강남구 테헤란로 45',
    shopDistance: '12km',
    shopImage: '/images/shops/shop3.png',
    phoneNumber: '05049763241',
  },
  {
    id: 4,
    name: '강아지 간식 치즈볼',
    weight: '500g',
    quantity: '2개',
    price: '15,000원',
    discountPrice: '12,000원',
    expiration: '25.12.01까지',
    category: '강아지',
    image: '/images/products/dog-snack.png',
    details: [
      '치즈 풍미 가득, 간식으로 적합',
      '소포장으로 신선도 유지',
      '모든 연령 강아지에게 적합',
    ],
    location: '서울특별시 강남구',
    distance: '12km',
    shopName: '강남동물병원',
    shopLocation: '서울특별시 강남구 테헤란로 45',
    shopDistance: '12km',
    shopImage: '/images/shops/shop4.png',
    phoneNumber: '05049763241',
  },

  // 고양이
  {
    id: 5,
    name: '고양이 사료 참치 레시피',
    weight: '4kg',
    quantity: '1개',
    price: '28,000원',
    discountPrice: '23,000원',
    expiration: '25.10.10까지',
    category: '고양이',
    image: '/images/products/cat-food.png',
    details: [
      '고단백 참치 기반, 건강한 근육 유지',
      '인공 색소 및 방부제 무첨가',
      '모든 생애주기 고양이 적합',
    ],
    location: '서울특별시 신림동',
    distance: '10km',
    shopName: '신림동물병원',
    shopLocation: '서울특별시 신림동 100-1',
    shopDistance: '10km',
    shopImage: '/images/shops/shop5.png',
    phoneNumber: '05049763241',
  },
  {
    id: 6,
    name: '고양이 간식 연어 스틱',
    weight: '300g',
    quantity: '3개',
    price: '12,000원',
    discountPrice: '10,000원',
    expiration: '25.11.20까지',
    category: '고양이',
    image: '/images/products/cat-snack.png',
    details: [
      '연어 스틱으로 맛과 영양 강화',
      '소포장으로 신선도 유지',
      '모든 연령 고양이 적합',
    ],
    location: '서울특별시 마포구',
    distance: '8km',
    shopName: '마포동물병원',
    shopLocation: '서울특별시 마포구 합정로 20',
    shopDistance: '8km',
    shopImage: '/images/shops/shop4.png',
    phoneNumber: '05049763241',
  },

  // 햄스터
  {
    id: 7,
    name: '햄스터 사료 혼합곡',
    weight: '500g',
    quantity: '1개',
    price: '8,000원',
    expiration: '25.09.30까지',
    category: '햄스터',
    image: '/images/products/hamster-food.png',
    details: ['혼합 곡물로 균형 잡힌 영양 제공', '소포장으로 신선도 유지'],
    location: '서울특별시 동작구',
    distance: '5km',
    shopName: '동작동물병원',
    shopLocation: '서울특별시 동작구 사당동 5-2',
    shopDistance: '5km',
    shopImage: '/images/shops/shop5.png',
    phoneNumber: '05049763241',
  },
  {
    id: 8,
    name: '햄스터 간식 해바라기씨',
    weight: '200g',
    quantity: '1개',
    price: '5,000원',
    expiration: '25.10.15까지',
    category: '햄스터',
    image: '/images/products/hamster-snack.png',
    details: ['해바라기씨로 단백질 공급', '소포장으로 신선도 유지'],
    location: '서울특별시 서초구',
    distance: '7km',
    shopName: '서초동물병원',
    shopLocation: '서울특별시 서초구 반포대로 30',
    shopDistance: '7km',
    shopImage: '/images/shops/clinic6.png',
    phoneNumber: '05049763241',
  },

  // 새
  {
    id: 9,
    name: '새 모이 혼합',
    weight: '1kg',
    quantity: '1개',
    price: '10,000원',
    expiration: '25.12.31까지',
    category: '새',
    image: '/images/products/bird-food.png',
    details: ['혼합 모이로 다양한 새 영양 제공'],
    location: '서울특별시 용산구',
    distance: '15km',
    shopName: '용산동물병원',
    shopLocation: '서울특별시 용산구 후암로 12',
    shopDistance: '15km',
    shopImage: '/images/shops/clinic7.png',
    phoneNumber: '05049763241',
  },
  {
    id: 10,
    name: '새 간식 과일칩',
    weight: '300g',
    quantity: '1개',
    price: '6,000원',
    expiration: '25.11.30까지',
    category: '새',
    image: '/images/products/bird-snack.png',
    details: ['과일칩으로 비타민과 미네랄 공급'],
    location: '서울특별시 강서구',
    distance: '20km',
    shopName: '강서동물병원',
    shopLocation: '서울특별시 강서구 화곡로 45',
    shopDistance: '20km',
    shopImage: '/images/shops/clinic8.png',
    phoneNumber: '05049763241',
  },

  // 고슴도치
  {
    id: 11,
    name: '고슴도치 사료 건조밀',
    weight: '500g',
    quantity: '1개',
    price: '14,000원',
    expiration: '25.10.20까지',
    category: '고슴도치',
    image: '/images/products/hedgehog-food.png',
    details: ['건조 밀로 영양 균형 제공'],
    location: '서울특별시 송파구',
    distance: '10km',
    shopName: '송파동물병원',
    shopLocation: '서울특별시 송파구 잠실로 10',
    shopDistance: '10km',
    shopImage: '/images/shops/clinic9.png',
    phoneNumber: '05049763241',
  },
  {
    id: 12,
    name: '고슴도치 간식 밀웜',
    weight: '200g',
    quantity: '1개',
    price: '7,000원',
    expiration: '25.12.01까지',
    category: '고슴도치',
    image: '/images/products/hedgehog-snack.png',
    details: ['밀웜으로 단백질 보충'],
    location: '서울특별시 노원구',
    distance: '12km',
    shopName: '노원동물병원',
    shopLocation: '서울특별시 노원구 상계로 20',
    shopDistance: '12km',
    shopImage: '/images/shops/clinic10.png',
    phoneNumber: '05049763241',
  },
];
